### ISSUE TITLE
PagedAttention tracking issue

### ISSUE THREAD

**Issue by EricLBuehler** [EricLBuehler/candle-vllm#11]
# Tracking issue for PagedAttention

## General overview
- [x] Use updated, refactored PagedAttention impl from vLLM
- [x] Implement attention biases
- [x] Implement `_memory_efficient_attention` or equiv.
  - Implement xtransformers memory efficient transformers: https://arxiv.org/abs/2112.05682
- [ ] Implement and use block cache (Scheduler, CacheEngine) in inference.
- [ ] Finalize FFI linking to compiled CUDA kernels
- [ ] Test PagedAttention in `llama` , `mistral` models

## `Sampler`
- [ ] Implement according to [this](https://github.com/vllm-project/vllm/blob/d940ce497e96bf86908248ea4b21417d0cf1c261/vllm/model_executor/layers/sampler.py)

## `ModulePipeline` refactoring
Need to redesign ModulePipeline design to integrate with the LLMEngine design. This means that a request output will be returned, and logprobs must be calculated.
- [ ] Calculate logprobs
- [ ] Generate `best_of` responses instead of the current `n` to check from (sorted by the logprobs)
- [ ] Use `Sampler`
- [ ] Do not return a ChatChoices, return something like a RawResponse that contains the logprobs, results
- [ ] Streaming poses a problem. This will need to be handled by the LLMEngine.
- [ ] Overall, convert ModulePipeline to a pure-sequence-generating platform

## LLM Engine
Manages calling the model pipeline and linking this with the KV cache. 
### Tasks
- [ ] Init cache by profiling model memory usage at maximum sequence length input. See: huggingface/candle#1412
- [x] Write the .generate function, the decoding entrypoint. The rough call chain looks like this, from vllm: 
  1) `.generate`: batch the input seqs, calling `.add_request`
  - [x] Write `.add_request`
  - [x] Write `.generate`
  2) `.run_engine`: `.step` through each unfinished request, recording output
  - [x] Write a `.has_unfinished_requests`
  - [x] Write `.run_engine`
  3) `.step`: 1) call Scheduler to manage the seqs to swap for this decoding phase with `._schedule`, then 2) execute the model
  - [x] Write a simple [`._schedule`](https://github.com/vllm-project/vllm/blob/60dc62dc9e53428912953276e0d12a034b353fb6/vllm/engine/llm_engine.py#L314)
  - [x] Write `.step`
  4) `.execute_model`: Follow the cache ops from `._schedule`, finally **run the model pipeline** with the cache.
  - Looks like the cache passes to the model pipeline has shared ownership with the CacheEngine. Will need to use Arc+my interior immutability setup.
  - [x] Write `.execute_model`

# Completed tasks

## SequenceGroup:
Sequences generated from the same prompt.
### Tasks
  - [x] Add a new seq grp to the Scheduler when a req is recieved.
    > https://github.com/vllm-project/vllm/blob/60dc62dc9e53428912953276e0d12a034b353fb6/vllm/engine/llm_engine.py#L252
  - [x] Add to this when a new seq is generated
    > https://github.com/vllm-project/vllm/blob/60dc62dc9e53428912953276e0d12a034b353fb6/vllm/engine/llm_engine.py#L429-L435

## Cache:
CacheEngine manages the KV cache.
### Tasks
  - [x] Ensure initialization is called

## BlockSpaceManager
Managed blocks and allocation
### Deps
- SequenceGroup
### Tasks
  - [x] BlockAllocator
  - [x] PhysicalTokenBlock
  - [x] BlockSpaceManager
    - [x] Allocation, in conjuction with a Scheduler impl

## Scheduler
Scheduler schedules blocks to swap in/out, copy.
### Deps
- SequenceGroup
- BlockSpaceManager
### Tasks
  - [x] SchedulerConfig
  - [x] BlockSpaceManager (with some deps: 1) Block Allocator)
    - [x] Allocation via BlockSpaceManager

**Comment by EricLBuehler** [comment]
`_memory_efficient_attention` is flash_attn when compiled with `--features cuda`, otherwise just normal `scaled_dot_product_attention`.

**Comment by EricLBuehler** [comment]
#13 added PagedAttention.

**Comment by EricLBuehler** [comment]
[this](d632948294b496f39a2f3f1b62ea163bbec697cb) commit adds most of the Scheduler functionality.

**Comment by EricLBuehler** [comment]
Completed tasks:

## Cache:
CacheEngine manages the KV cache.
### Tasks
  - [x] Ensure initialization is called

## BlockSpaceManager
Managed blocks and allocation
### Deps
- SequenceGroup
### Tasks
  - [x] BlockAllocator
  - [x] PhysicalTokenBlock
  - [x] BlockSpaceManager
    - [x] Allocation, in conjuction with a Scheduler impl

## Scheduler
Scheduler schedules blocks to swap in/out, copy.
### Deps
- SequenceGroup
- BlockSpaceManager
### Tasks
  - [x] SchedulerConfig
  - [x] BlockSpaceManager (with some deps: 1) Block Allocator)
    - [x] Allocation via BlockSpaceManager

**Comment by EricLBuehler** [comment]
Closing this pending a rewrite of the scheduler and cache, see the [scheduler](https://github.com/EricLBuehler/candle-vllm/tree/scheduler) branch. A new tracking issue will be reopened.
