### ISSUE TITLE
KV Cache and Scheduler tracking issue

### ISSUE THREAD

**Issue by EricLBuehler** [EricLBuehler/candle-vllm#14]
This is a tracking issue for the KV cache and its associated scheduler. Note that batching is handled by the scheduler.

## Short-term overview
- [x] Add basic framework
  - [x] Scheduler
  - [x] CacheEngine
- [x] Implement the Scheduler
  - [x] Implement BlockEngine to determine allocation capacity
  - [x] Use SequenceGroup to prepare for future sampling methods
  - [x] Add preemption method
  - [x] Add method to possibly allocate a slot
  - [x] Add swapping in
- [x] Use scheduled blocks
  - [x] FFI calls to the vLLM CUDA kernels for swapping, copying blocks - thanks @sigma-andex for [their FFI development](https://github.com/sigma-andex/candle-vllm-fix)
  - [x] Schedule new blocks on each token generation cycle
  - [x] Prepare inputs for input, decode

**Comment by EricLBuehler** [comment]
This major stage of development is finally done.
