### ISSUE TITLE
PagedAttention tracking issue

### ISSUE THREAD

**Issue by EricLBuehler** [EricLBuehler/candle-vllm#9]
This is the tracking issue for PagedAttention. Please see the [paged_attention](https://github.com/EricLBuehler/candle-vllm/tree/paged_attention) branch.

- [ ] Implement `multi_kv_attention`
  - [ ] Implement xtransformers memory efficient transformers: https://arxiv.org/abs/2112.05682
- [ ] Finalize FFI linking to compiled CUDA kernels
- [ ] Use of PagedAttention in `llama` model
